apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: chroma
  name: chroma
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chroma
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: chroma
    spec:
      containers:
        - image: ghcr.io/chroma-core/chroma:latest
          name: chroma
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /chroma/chroma
              name: chroma-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: chroma-cm0
          name: chroma-cm0
