apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: db-like
  name: db-like
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-like
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: db-like
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: like_db
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
          image: postgres:15
          name: postgres-db-like
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
