apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: like
  name: like
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: like
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: like
    spec:
      containers:
        - env:
            - name: API_GATEWAY_URL
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
            - name: JWT_SECRET
            - name: KAFKA_BROKER
            - name: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
          image: like-service:1.0
          name: like-service
          ports:
            - containerPort: 9999
              protocol: TCP
            - containerPort: 5005
              protocol: TCP
      restartPolicy: Always
