apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: product
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: product
    spec:
      containers:
        - env:
            - name: API_GATEWAY_URL
            - name: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
            - name: CLOUDINARY_CLOUD_NAME
            - name: EUREKA_CLIENT_SERVICE_URL
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
            - name: JWT_SECRET
            - name: KAFKA_BROKER
            - name: MONGO_URI
          image: product-service:1.0
          name: product-service
          ports:
            - containerPort: 8999
              protocol: TCP
            - containerPort: 5005
              protocol: TCP
      restartPolicy: Always
