# Use the official Python image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /recc_system_2

# Copy requirements.txt into the container
COPY requirements.txt /recc_system_2/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /recc_system_2

# Expose the port your Flask app runs on
EXPOSE 5001

# Set the environment variable for Flask
ENV FLASK_APP=app-recc2.py
ENV FLASK_ENV=production

# Command to run the Flask app
CMD ["flask", "run", "--host=0.0.0.0", "--port=5001"]
