from recc_system_2.app.settings import MONGO_URI, MONGO_DB_NAME, MONGO_COLLECTION_NAME_REVIEWS,MONGO_COLLECTION_NAME_PRODUCTS, MYSQL_CONNECTION_STRING, NUM_PRODUCTS

class Config:
    MONGO_URI = MONGO_URI
    MONGO_DB_NAME = MONGO_DB_NAME
    MONGO_COLLECTION_NAME_PRODUCTS = MONGO_COLLECTION_NAME_PRODUCTS
    MONGO_COLLECTION_NAME_REVIEWS = MONGO_COLLECTION_NAME_REVIEWS
    MYSQL_CONNECTION_STRING = MYSQL_CONNECTION_STRING
    NUM_PRODUCTS=NUM_PRODUCTS
