from app.settings import MONGO_URI, MONGO_DB_NAME, MONGO_COLLECTION_NAME, MYSQL_CONNECTION_STRING

class Config:
    MONGO_URI = MONGO_URI
    MONGO_DB_NAME = MONGO_DB_NAME
    MONGO_COLLECTION_NAME = MONGO_COLLECTION_NAME
    MYSQL_CONNECTION_STRING = MYSQL_CONNECTION_STRING
