package org.example.product.enums;

public enum DetailKey {
    ACTIVE_INGREDIENTS,
    BRAND,
    DATE_FIRST_AVAILABLE,
    DEPARTMENT,
    DOSAGE_FORM,
    FLAVOR,
    IS_DISCONTINUED_BY_MANUFACTURER,
    ITEM_FORM,
    ITEM_MODEL_NUMBER,
    MANUFACTURER,
    MATERIAL,
    PACKAGE_DIMENSIONS,
    PACKAGE_INFORMATION,
    UNIT_COUNT,
    AGE_RANGE,
    HEAD_TYPE,
    ITEM_WEIGHT,
    MATERIAL_FEATURE,
    PRODUCT_BENEFITS,
    BATTERIES,
    NUMBER_OF_BLADES,
    PRODUCT_DIMENSIONS,
    BLADE_MATERIAL,
    NUMBER_OF_ITEMS;
}
